### ISSUE TITLE
Unable to load application

### ISSUE THREAD

**Issue by kirantpatil** [evgeniy-khatko/tarantula#10]
Unable to load Tarantula app with puma 2.3.2 server.
## Error message:

kiran@patchbee:~$ sudo service fossqc start
Puma starting in single mode...
- Version 2.3.2, codename: Delicious Thin Mints
- Min threads: 0, max threads: 16
- Environment: production
  ! Unable to load application
  /home/fossqc/tarantula/app/models/bug_tracking/jira_integration/jira_issue.rb:3:in `<class:JiraIssue>': undefined method`adapter' for nil:NilClass (NoMethodError)
  from /home/fossqc/tarantula/app/models/bug_tracking/jira_integration/jira_issue.rb:1:in `<top (required)>'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`require'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block in require'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in`load_dependency'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:359:in`require_or_load'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:313:in `depend_on'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:225:in`require_dependency'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/engine.rb:439:in `block (2 levels) in eager_load!'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/engine.rb:438:in`each'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/engine.rb:438:in `block in eager_load!'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/engine.rb:436:in`each'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/engine.rb:436:in `eager_load!'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/application/finisher.rb:53:in`block in module:Finisher'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `instance_exec'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/initializable.rb:30:in`run'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/initializable.rb:54:in`each'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `run_initializers'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/application.rb:136:in`initialize!'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in `method_missing'
  from /home/fossqc/tarantula/config/environment.rb:4:in`<top (required)>'
  from config.ru:4:in `require'
  from config.ru:4:in`block in <main>'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/rack-1.4.1/lib/rack/builder.rb:51:in`initialize'
  from config.ru:1:in `new'
  from config.ru:1:in`<main>'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/rack-1.4.1/lib/rack/builder.rb:40:in `eval'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/rack-1.4.1/lib/rack/builder.rb:40:in`parse_file'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/puma-2.3.2/lib/puma/configuration.rb:91:in `app'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/puma-2.3.2/lib/puma/runner.rb:101:in`load_and_bind'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/puma-2.3.2/lib/puma/single.rb:62:in `run'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/puma-2.3.2/lib/puma/cli.rb:432:in`run'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/puma-2.3.2/bin/puma:10:in `<top (required)>'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/bin/puma:19:in`load'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/bin/puma:19:in `<main>'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in`eval'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by evgeniy-khatko** [comment]
This issue does not depend on the application server being used. It should be fixed now in master

**Comment by kirantpatil** [comment]
Thanks, I will recheck and get back to you

**Comment by kirantpatil** [comment]
Hi,

I did git pull and I am still getting the same error.

fossqc@patchbee:~/tarantula$ git log
commit e2a01a964e7c2d72ac4ad190b47625f33490154d
Author: ekhatko ekhatko@at-consulting.ru
Date:   Thu Jul 25 14:12:12 2013 +0400

```
: fix
```

commit f16ac72445e32af25d6c2feb37b74db810777fb0
Author: ekhatko ekhatko@at-consulting.ru
Date:   Wed Jul 24 17:53:30 2013 +0400

```
AT updts
```

commit de7d419ebcdca3addfd4cfb9d96303b9c03eae6e
Author: ekhatko ekhatko@at-consulting.ru
Date:   Wed Jul 24 17:32:58 2013 +0400

```
AT updates
```

## Error log at terminal

kiran@patchbee:~$ sudo service fossqc start
Puma starting in single mode...
- Version 2.3.2, codename: Delicious Thin Mints
- Min threads: 0, max threads: 16
- Environment: production
  ! Unable to load application
  /home/fossqc/tarantula/app/models/bug_tracking/jira_integration/jira_issue.rb:3:in `<class:JiraIssue>': undefined method`adapter' for nil:NilClass (NoMethodError)
  from /home/fossqc/tarantula/app/models/bug_tracking/jira_integration/jira_issue.rb:1:in `<top (required)>'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`require'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block in require'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in`load_dependency'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:359:in`require_or_load'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:313:in `depend_on'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:225:in`require_dependency'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/engine.rb:439:in `block (2 levels) in eager_load!'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/engine.rb:438:in`each'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/engine.rb:438:in `block in eager_load!'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/engine.rb:436:in`each'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/engine.rb:436:in `eager_load!'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/application/finisher.rb:53:in`block in module:Finisher'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `instance_exec'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/initializable.rb:30:in`run'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/initializable.rb:54:in`each'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `run_initializers'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/application.rb:136:in`initialize!'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in `method_missing'
  from /home/fossqc/tarantula/config/environment.rb:4:in`<top (required)>'
  from config.ru:4:in `require'
  from config.ru:4:in`block in <main>'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/rack-1.4.1/lib/rack/builder.rb:51:in`initialize'
  from config.ru:1:in `new'
  from config.ru:1:in`<main>'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/rack-1.4.1/lib/rack/builder.rb:40:in `eval'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/rack-1.4.1/lib/rack/builder.rb:40:in`parse_file'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/puma-2.3.2/lib/puma/configuration.rb:91:in `app'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/puma-2.3.2/lib/puma/runner.rb:101:in`load_and_bind'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/puma-2.3.2/lib/puma/single.rb:62:in `run'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/puma-2.3.2/lib/puma/cli.rb:432:in`run'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/gems/puma-2.3.2/bin/puma:10:in `<top (required)>'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/bin/puma:19:in`load'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/bin/puma:19:in `<main>'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in`eval'
  from /home/fossqc/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by evgeniy-khatko** [comment]
I've fixed the issue, thanks!
I've also slightly changed INSTALL instructions...
Could you please verify the fix.

**Comment by kirantpatil** [comment]
Yes, I will verify the fix.

**Comment by kirantpatil** [comment]
Now app loads on Puma server

Thanks.
